### ISSUE TITLE
Uno Zen / Urban attribution

### ISSUE THREAD

**Issue by daleanthony** [Kikobeats/uno-urban#2]
Hey dude,

It's really great to see what you have done with Uno and the effort you have put into maintaining both the free and premium Urban version, however the [original licence](http://creativecommons.org/licenses/by/4.0/) stated that attribution / appropriate credit with a [link](http://dale.does.design) must remain in place within the template and any documentation, I notice that this isn't present in either theme. Would you mind adding it back in some form?

Happy to discuss over email if you prefer dale[at]does.design

**Comment by Kikobeats** [comment]
I think that the attribution link is correctly present into [Uno Zen Mainpage](https://github.com/Kikobeats/uno-zen/blob/master/README.md):

> Uno Zen is a fork of Uno for Ghost [LINK] that provides some features missing in the original theme.

I didn't add the link here on this documentation because this version isn't based in Uno, is based in Uno Zen as commercial iteration, but I can add add a section about the different version of Uno and licensing of each of them.

**Comment by daleanthony** [comment]
Thanks for the reply, hope you had a good weekend

The creative commons license is actually referring to the attribution and link that was present in the footer of the theme itself, this would also apply to the commercial version as it's still a fork of the Uno theme

**Comment by Kikobeats** [comment]
@daleanthony not really, it's more your open interpretation of the creative commons:

> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

Seriously, that is the things that I explain in the Uno Zen main page. I don't think ghost footer is a good place for this.

**Comment by daleanthony** [comment]
@Kikobeats from the [full license](http://creativecommons.org/licenses/by/4.0/legalcode):

> 1. a. retain the following **if it is supplied by the Licensor** with the Licensed Material:
> 
> identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);

I don't mean to be a dick, but I am the licensor, this is what I’m requesting, the attribution shouldn't have been removed from the footer in the first place.

You've replaced the footer text with your own which gives the impression that you are solely responsible for the design and code of the commercial version, which is not true. If you change the core design (but keep the code) I'd happily compromise and allow you to change the footer.

**Comment by Kikobeats** [comment]
Uno → 25 commits
Uno Zen → +400 commits

Are you sure that have the original design? are you check the codebase first?

For me is especially funny because original CSS/HTML scaffold was a totally disaster and I put much effort in refactor it.

Sorry I don't want to change footer.

**Comment by opattison** [comment]
I don’t think @daleanthony has an incorrect interpretation of the CC-BY license. It’s an extremely permissive license, but giving attribution and a link are required when repurposing licensed content.

> Are you sure that have the original design? are you check the codebase first?
> 
> original CSS/HTML scaffold was a totally disaster

I think this is disingenuous. Which is it: that the design is yours originally or that the re-implementation of a non-original implementation took a lot of work? Either way, that doesn’t have much to do with Creative Commons attribution, since the license deals with design, not code.

Credit in the readme and docs would be appropriate.

**Comment by Kikobeats** [comment]
I'm open to include licensing attribution in Uno Urban as well, but I don't feel confortable extending footer because for me is not a good place for this kind of things.

Even originally design is made by @daleanthony, we codebase change a LOT and [more people](https://github.com/Kikobeats/uno-zen/graphs/contributors) help me to have better design/code.

Consider make a PR with the licensing changes that you consider appropiate and we talk based on it.

**Comment by Kikobeats** [comment]
Hey guys, I did a misinterpretation of that. I talked with @daleanthony  and now he appears on both footers as original design. 

I hope everyone is happy now!
