### ISSUE TITLE
Left Navigation doesn't show up

### ISSUE THREAD

**Issue by ghost** [Kikobeats/uno-urban#7]
It seems like the left navigation isn't showing up.

I also checked it on your blog.

I can only see the link to the right for the previous article. 

I can click on the left link but can't see it.

**Comment by Kikobeats** [comment]
Can you upload an screenshot? I don't see your point about that

**Comment by ghost** [comment]
![2016-05-14-101840_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/15267273/83bba4e4-19bd-11e6-8a9a-a327c6e16405.png)

**Comment by Kikobeats** [comment]
@ndalliard strange because I see it fine:

<img width="1280" alt="screen shot 2016-05-14 at 13 56 23" src="https://cloud.githubusercontent.com/assets/2096101/15268347/b4a9ecc8-19db-11e6-9780-066dd79edb06.png">

Please say me:
- browser and version
- os and version
- open devtools and check for errors

**Comment by ghost** [comment]
Strange yes. I use:

Chromium 50.0.2661.102
ArchLinux 4.5.4-1
No errors in devtools

**Edit:** I just checked it on my iMac with Safari. It works there.

**Comment by ghost** [comment]
Oh wow. I got it. I've set the font size in the chromium settings to large. That was causing the problem. Font size on normal works fine and both links show up on the right place!

**Comment by Kikobeats** [comment]
Perfect! :-)
